all:
	gcc source/child.c -o bin/child
	gcc source/childfaulter.c -o bin/childfaulter
	gcc source/childtime.c -o bin/childtime
	echo "Done compiling"

clean:
	rm -f bin/child
	rm -f bin/childfaulter
	rm -f bin/childtime
	echo "Done cleaning"